export const loginConstants = {
    LOGIN_API : "",
    LOGIN_SAGA : "lOGIN_SAGA",
    LOGIN_RESPOSE : "LOGIN_RESPOSE",
    LOGIN_REQUEST : "LOGIN_REQUEST",
    
    LOGOUT_API : "",
    LOGOUT_SAGA : "LOGOUT_SAGA",
    LOGOUT_REQUEST : "LOGOUT_REQUEST",
    LOGOUT_RESPONSE  : "LOGOUT_RESPONSE",
    
    GET_LOGIN_DETAIL_API : "",
    GET_LOGIN_DETAIL_SAGA : "GET_LOGIN_DETAIL_SAGA",
    GET_LOGIN_DETAIL_REQUEST : "GET_LOGIN_DETAIL_REQUEST",
    GET_LOGIN_DETAIL_RESPONSE : "GET_LOGIN_DETAIL_RESPONSE"
}